version: '3.8'
services:
  watch-directory:
    env_file:
      - .env
    build: ./
    container_name: watch-directory
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/usr/src/app




